#!/usr/bin/env python3
"""
Railway cron entrypoint for automated ESMA updates.

Runs the full update pipeline and prints a concise summary from the JSON report.
Exit code behavior:
  - 0: update pipeline completed (with or without new data)
  - non-zero: pipeline failed
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Dict


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REPORT_PATH = Path("/tmp/update_report.json")


def load_report(report_path: Path) -> Dict[str, Any] | None:
    """Read update report JSON when present."""
    if not report_path.exists():
        return None

    try:
        with report_path.open("r", encoding="utf-8") as report_file:
            return json.load(report_file)
    except (OSError, json.JSONDecodeError) as exc:
        print(f"[cron] Warning: Could not read report at {report_path}: {exc}")
        return None


def print_report_summary(report: Dict[str, Any]) -> None:
    """Print a compact update summary for Railway logs."""
    summary = report.get("summary", {})
    successful = int(summary.get("successful", 0))
    skipped = int(summary.get("skipped", 0))
    failed = int(summary.get("failed", 0))
    total_entities = int(summary.get("total_entities", 0))

    print("[cron] Update summary")
    print(f"[cron] successful={successful} skipped={skipped} failed={failed} total_entities={total_entities}")

    for result in report.get("results", []):
        register_type = str(result.get("register_type", "unknown")).upper()
        if result.get("success"):
            status = "updated"
        elif result.get("skipped"):
            status = "skipped"
        else:
            status = "failed"
        entities_imported = result.get("entities_imported")
        print(f"[cron] {register_type}: status={status} entities={entities_imported}")


def run_update(report_path: Path = DEFAULT_REPORT_PATH) -> int:
    """Execute update_all_registers.py and return its exit code."""
    if report_path.exists():
        report_path.unlink()

    cmd = [
        sys.executable,
        "scripts/update_all_registers.py",
        "--all",
        "--report",
        str(report_path),
    ]

    print("[cron] Running ESMA full update pipeline...")
    print(f"[cron] Command: {' '.join(cmd)}")

    completed = subprocess.run(
        cmd,
        cwd=str(PROJECT_ROOT),
        check=False,
    )

    report = load_report(report_path)
    if report:
        print_report_summary(report)
        successful = int(report.get("summary", {}).get("successful", 0))
        if completed.returncode == 0 and successful == 0:
            print("[cron] No new register updates detected.")
        elif completed.returncode == 0:
            print("[cron] Register updates imported successfully.")
    else:
        print("[cron] No report generated by pipeline.")

    if completed.returncode != 0:
        print(f"[cron] Pipeline failed with exit code {completed.returncode}.")
        return completed.returncode

    print("[cron] Pipeline finished successfully.")
    return 0


def main() -> int:
    return run_update()


if __name__ == "__main__":
    sys.exit(main())
